#!/usr/bin/python3
import math
import random
import plotly.graph_objects as go

Route = [1, 5, 9, 13, 33, 104, 4192];
Trip  = [0, 1, 2,  3,  4,   5,    6];

#               X Y Z
coordinates = [[0,0,0], #1
[3,14,3], # 5
[4,2,1], # 9
[2,5,3], # 13
[13,7,1], # 33
[12,2,2], # 104
[8,5,4]] # 4192

def dist(p1,p2):
 return math.sqrt( (p1[0]-p2[0])*(p1[0]-p2[0]) + (p1[1]-p2[1])*(p1[1]-p2[1]) + (p1[2]-p2[2])*(p1[2]-p2[2]) )

Trip_min = ""
Trip_len_min = 99999999999

for n in range(1,100):
 Trip_len = 0;
 Trip_help = Trip[1:]
 random.shuffle(Trip_help);
 Trip[1:] = Trip_help

 for i in range(0,len(Trip)-1):
  Trip_len += dist(coordinates[Trip[i]],coordinates[Trip[i+1]])

 print( str(n)+" "+str(Trip_len) + " " + str(Trip) )
 if Trip_len_min > Trip_len:
  Trip_min = Trip[:];
  Trip_len_min = Trip_len;
  print('-')
  
print()
print( str(Trip_len_min) + " " + str(Trip_min) )

xx = []
yy = []
for n in Trip_min:
 xx.append(coordinates[n][0])
 yy.append(coordinates[n][1])

# Plot
fig = go.Figure()

fig.update_layout(paper_bgcolor="#000000")
fig.update_layout(plot_bgcolor ="#000000")
fig.update_xaxes(showline=True, linewidth=1, linecolor='black', gridcolor='grey',zeroline=True, zerolinewidth=2, zerolinecolor='grey')
fig.update_yaxes(showline=True, linewidth=1, linecolor='black', gridcolor='grey',zeroline=True, zerolinewidth=2, zerolinecolor='grey')
fig.update_layout(yaxis=dict(scaleanchor="x", scaleratio=1))

fig.add_trace(go.Scatter(x=xx, y=yy, mode='markers+lines', name='Trip',
                                     marker=dict(color='#3dc9b3',size=10,
                                     line=dict(width=2,color='#808080')) ))

fig.show()
